package server

var dashboardHTML = []byte(`<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Stockyard Codex</title><style>:root{--bg:#1a1410;--surface:#241c15;--border:#3d2e1e;--rust:#c4622d;--leather:#8b5e3c;--cream:#f5e6c8;--muted:#7a6550;--text:#e8d5b0}*{box-sizing:border-box;margin:0;padding:0}body{background:var(--bg);color:var(--text);font-family:'JetBrains Mono',monospace,sans-serif;min-height:100vh}header{background:var(--surface);border-bottom:1px solid var(--border);padding:1rem 2rem;display:flex;align-items:center;gap:1rem}.logo{color:var(--rust);font-size:1.25rem;font-weight:700}.badge{background:var(--rust);color:var(--cream);font-size:0.65rem;padding:0.2rem 0.5rem;border-radius:3px;font-weight:600;text-transform:uppercase}main{max-width:1100px;margin:0 auto;padding:2rem}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-bottom:2rem}.stat{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:1.25rem;text-align:center}.stat-value{font-size:1.75rem;font-weight:700;color:var(--rust)}.stat-label{font-size:0.75rem;color:var(--muted);margin-top:0.25rem;text-transform:uppercase;letter-spacing:0.05em}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.card{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:1.5rem}.card h2{font-size:0.85rem;color:var(--muted);text-transform:uppercase;letter-spacing:0.08em;margin-bottom:1rem}.form-row{display:flex;gap:0.5rem;margin-bottom:0.75rem;flex-wrap:wrap;align-items:flex-start}select,input,textarea{background:var(--bg);border:1px solid var(--border);color:var(--text);padding:0.5rem 0.75rem;border-radius:4px;font-family:inherit;font-size:0.85rem}.form-row select,.form-row input{flex:1}textarea{width:100%;min-height:80px;resize:vertical}.btn{background:var(--rust);color:var(--cream);border:none;padding:0.5rem 1rem;border-radius:4px;cursor:pointer;font-family:inherit;font-size:0.85rem;font-weight:600}.btn:hover{opacity:0.85}.btn-sm{padding:0.25rem 0.6rem;font-size:0.75rem}.btn-danger{background:#7a2020}table{width:100%;border-collapse:collapse;font-size:0.82rem}th{text-align:left;color:var(--muted);padding:0.5rem;border-bottom:1px solid var(--border);font-size:0.75rem;text-transform:uppercase}td{padding:0.5rem;border-bottom:1px solid var(--border)}.empty{color:var(--muted);font-size:0.85rem;padding:1rem 0;text-align:center}.full{grid-column:1/-1}.badge-g{background:#1a3a1a;color:#5cb85c;border:1px solid #2d5a2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}.badge-r{background:#3a1a1a;color:#d9534f;border:1px solid #5a2d2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}.badge-y{background:#3a2f1a;color:#f0ad4e;border:1px solid #5a4a2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}</style></head>
<body><header><span class="logo">&#x2B21; Stockyard</span><span style="color:var(--muted)">/</span><span style="color:var(--cream);font-weight:600">Codex</span><span class="badge">Internal Wiki</span></header>
<main><div class="stats"><div class="stat"><div class="stat-value" id="s1">0</div><div class="stat-label">Pages</div></div><div class="stat"><div class="stat-value" id="s2">0</div><div class="stat-label">Edits</div></div><div class="stat"><div class="stat-value" id="s3">FREE</div><div class="stat-label">Tier</div></div></div><div class="grid">
<div class="card"><h2>New Page</h2>
<div class="form-row"><input id="f-title" placeholder="Page title"></div>
<div class="form-row"><input id="f-slug" placeholder="slug (auto from title)"></div>
<div class="form-row"><input id="f-tags" placeholder="tag1, tag2"></div>
<textarea id="f-content" placeholder="Page content (markdown-ish)"></textarea>
<button class="btn" style="margin-top:0.5rem" onclick="createPage()">Create Page</button></div>
<div class="card"><h2>Search</h2>
<div class="form-row"><input id="f-search" placeholder="Search pages..." oninput="searchPages()"></div>
<div id="search-results"></div></div>
<div class="card full"><h2>All Pages</h2>
<table><thead><tr><th>Title</th><th>Tags</th><th>Updated</th><th>Wiki URL</th><th></th></tr></thead>
<tbody id="pages-body"><tr><td colspan="5" class="empty">No pages</td></tr></tbody></table></div>
<div class="card full" id="edit-panel" style="display:none">
<h2>Editing: <span id="edit-title-label" style="color:var(--cream)"></span></h2>
<div class="form-row"><input id="e-title" placeholder="Title"></div>
<div class="form-row"><input id="e-tags" placeholder="tags"></div>
<textarea id="e-content" style="min-height:200px"></textarea>
<button class="btn" style="margin-top:0.5rem" onclick="savePage()">Save</button>
<button class="btn btn-danger btn-sm" style="margin-top:0.5rem;margin-left:0.5rem" onclick="document.getElementById('edit-panel').style.display='none'">Cancel</button>
</div>
</div></main>
<script>
async function api(m,p,bd){var o={method:m,headers:{"Content-Type":"application/json"}};if(bd)o.body=JSON.stringify(bd);var r=await fetch(p,o);try{return await r.json();}catch(e){return {};}}  
var editingId=null;
async function load(){var s=await api("GET","/api/stats");var l=await api("GET","/api/limits");document.getElementById("s1").textContent=s.pages||0;document.getElementById("s3").textContent=(l.tier||"free").toUpperCase();loadPages();}
async function loadPages(){var data=await api("GET","/api/pages");var tbody=document.getElementById("pages-body");if(!data||!data.length){tbody.innerHTML="<tr><td colspan='5' class='empty'>No pages</td></tr>";return;}tbody.innerHTML=data.map(function(p){return "<tr><td style='color:var(--cream)'>"+p.title+"</td><td style='font-size:0.75rem;color:var(--muted)'>"+p.tags+"</td><td style='font-size:0.75rem;color:var(--muted)'>"+new Date(p.updated_at).toLocaleDateString()+"</td><td><a href='/wiki/"+p.slug+"' target='_blank' style='color:var(--leather);font-size:0.8rem'>/wiki/"+p.slug+"</a></td><td style='display:flex;gap:0.25rem'><button class='btn btn-sm' onclick='editPage("+p.id+")'>Edit</button><button class='btn btn-sm btn-danger' onclick='deletePage("+p.id+")'>Del</button></td></tr>";}).join("");}
async function createPage(){var p={title:document.getElementById("f-title").value.trim(),slug:document.getElementById("f-slug").value.trim(),tags:document.getElementById("f-tags").value.trim(),content:document.getElementById("f-content").value.trim()};if(!p.title){alert("Title required");return;}var res=await api("POST","/api/pages",p);if(res.error){alert(res.error);return;}document.getElementById("f-title").value="";document.getElementById("f-content").value="";load();}
async function editPage(id){var p=await api("GET","/api/pages/"+id);editingId=id;document.getElementById("edit-panel").style.display="block";document.getElementById("edit-title-label").textContent=p.title;document.getElementById("e-title").value=p.title;document.getElementById("e-tags").value=p.tags;document.getElementById("e-content").value=p.content;}
async function savePage(){if(!editingId)return;var p={title:document.getElementById("e-title").value.trim(),tags:document.getElementById("e-tags").value.trim(),content:document.getElementById("e-content").value.trim()};var res=await api("PUT","/api/pages/"+editingId,p);if(res.error){alert(res.error);return;}document.getElementById("edit-panel").style.display="none";editingId=null;load();}
async function searchPages(){var q=document.getElementById("f-search").value.trim();if(!q){document.getElementById("search-results").innerHTML="";return;}var data=await api("GET","/api/search?q="+encodeURIComponent(q));var el=document.getElementById("search-results");if(!data||!data.length){el.innerHTML="<div style='font-size:0.82rem;color:var(--muted);padding:0.5rem 0'>No results</div>";return;}el.innerHTML=data.map(function(p){return "<div style='padding:0.4rem 0;border-bottom:1px solid var(--border)'><a href='/wiki/"+p.slug+"' target='_blank' style='color:var(--cream);font-size:0.85rem'>"+p.title+"</a></div>";}).join("");}
async function deletePage(id){if(!confirm("Delete page?"))return;await api("DELETE","/api/pages/"+id);load();}
load();
</script></body></html>`)
